### ISSUE TITLE
Open to interoperability with other todos in markdown projects?

### ISSUE THREAD

**Issue by chmac** [kt3k/todo-md#63]
There's a [small group](https://github.com/GenerousLabs/git-markdown-spec/issues/1) forming of different projects that are working together to try and find a simple format to store tasks in markdown, with the ambition to achieve interoperability between our assorted projects.

Is it crazy to add your view-todo project to the mix?

**Comment by kt3k** [comment]
Sorry, I don't think that's a good idea because I don't develop nor use this tool anymore.

BTW your approach sounds very interesting 👍 Good luck on your project.

**Comment by chmac** [comment]
@kt3k Makes sense, thanks for the quick reply. 👍
